# -*- coding: utf-8 -*-
"""Data Science/AI Tutor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rt_2c6MtgN57IBykIuhCtu9ZOWsV-vM0
"""

! streamlit run app.py & npx localtunnel --port 8501

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com